#!/bin/bash -l

# Set working directory to home directory
cd "${HOME}"

# Launch FVWM
FVWM_ASSETS_ROOT="${ROOT}/bc_fvwm_assets/template"
FVWM_ROOT="${FVWM_ASSETS_ROOT}" "${FVWM_ASSETS_ROOT}/fvwm_wrapper" -f "${ROOT}/fvwm/fvwmrc" &

# Load the MATLAB module
module load ${MATLAB_MODULE}

#
# Start MATLAB
#

matlab -desktop

# Kill vncserver when user closes GUI
vncserver -kill ${DISPLAY}
