#!/bin/bash -l

# Set working directory to home directory
cd "${HOME}"

# Restore the module environment to avoid conflicts
module restore

#
# Launch Fluxbox
#

FLUXBOX_RC_FILE="${PBS_O_WORKDIR}/${PBS_JOBID}.rc"
FLUXBOX_ASSETS_ROOT="${ROOT}/fluxbox"

# Build Fluxbox init file
cat > "${FLUXBOX_RC_FILE}" << EOT
session.configVersion: 13
session.screen0.toolbar.widthPercent: 60
session.screen0.toolbar.tools: prevworkspace, workspacename, nextworkspace, iconbar, systemtray, prevwindow, nextwindow, clock
session.menuFile: $FLUXBOX_ASSETS_ROOT/menu
session.keyFile: $FLUXBOX_ASSETS_ROOT/keys
session.styleOverlay: $FLUXBOX_ASSETS_ROOT/overlay
EOT

# Export the module function for the terminal
[[ $(type -t module) == "function" ]] && export -f module

# Start the Fluxbox window manager
FLUXBOX_ASSETS_ROOT="${FLUXBOX_ASSETS_ROOT}" fluxbox -display "${DISPLAY}.0" -rc "${FLUXBOX_RC_FILE}" &

#
# Start MATLAB
#

# Load the MATLAB module
module load ${MATLAB_MODULE}

# Launch MATLAB
matlab -desktop

# Kill vncserver when user closes GUI
vncserver -kill ${DISPLAY}
