#!/bin/bash -l

# Read in any user defined X resources
[[ -e "${HOME}/.Xresources" ]] && xrdb "${HOME}/.Xresources"

# Set background to grey
xsetroot -solid grey

# Export the module function for the terminal
[[ $(type -t module) == "function" ]] && export -f module

# Launch FVWM
exec fvwm "$@"
